- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: cloudcenter.corp/europe/almpre/nexus
  id: cloudcenter.corp.europe.almpre.nexus.nexus-config-specific-repo
  loglevel: INFO
  name: Nexus - Config-Create SPECIFIC Proxy Repo
  nodeFilterEditable: false
  options:
  - name: inventories-branch
    required: true
    value: master
  - name: source-branch
    required: true
    value: master
  - hidden: true
    label: Inventario del proyecto Inventario
    name: inventory-path
    required: true
    value: inventories/almmc
  - hidden: true
    label: Grupo Ansible
    name: launchHost
    required: true
    value: nexus_proxy_almpre
  - hidden: true
    label: Ruta del Playbook
    name: playbook
    required: true
    value: playbooks/nexus3-check-repos.yml

  - name: ignore_errors
    required: true
    value: 'True'
    values:
     - 'false'
     - 'true'
    valuesListDelimiter: ','

  - label: Nombre Repo que queremos tratar
    name: nexus-repo-name
    required: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        gitBaseDirectory: /opt/rundeck/${job.id}/sources
        gitBranch: ${option.source-branch}
        gitPasswordPath: keys/gitpass
        gitUrl: https://c3almadm@github.alm.europe.cloudcenter.corp/ccc-almmulticloud-community/ansible-nexus-multicloud.git
        gitUseProjectBasedSubdirectory: 'false'
        strictHostKeyChecking: 'yes'
      nodeStep: false
      type: git-clone-step
    - configuration:
        gitBaseDirectory: /opt/rundeck/${job.id}/inventories
        gitBranch: ${option.inventories-branch}
        gitPasswordPath: keys/gitpass
        gitUrl: https://c3almadm@github.alm.europe.cloudcenter.corp/ccc-ansible-multicloud/ansible-nexus-almmc-inventory.git
        gitUseProjectBasedSubdirectory: 'false'
        strictHostKeyChecking: 'yes'
      nodeStep: false
      type: git-clone-step
    - configuration:
        ansible-base-dir-path: /opt/rundeck/${job.id}/sources
        ansible-become: 'false'
        ansible-disable-limit: 'false'
        ansible-extra-param: -i /opt/rundeck/${job.id}/${option.inventory-path} -l
          ${option.launchHost}
        ansible-extra-vars: '{"launchHosts": "${option.launchHost}", "nexus3_ansible_inventory_tag":
          "${option.inventories-branch}", "nexus3_ansible_source_tag": "${option.source-branch}",
          "test_script_ignore_errors": "${option.ignore_errors}" ,  "limit_repository":
          "${option.nexus-repo-name}"}'
        ansible-playbook: ${option.playbook}
        ansible-ssh-auth-type: privateKey
        ansible-ssh-key-storage-path: keys/ssh/almrundeck-private-key
        ansible-ssh-use-agent: 'false'
        ansible-ssh-user: almrundeck
        ansible-vault-storage-path: keys/vault/ansible-nexus-almmc-inventory
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    keepgoing: false
    strategy: node-first
  uuid: cloudcenter.corp.europe.almpre.nexus.nexus-config-specific-repo
